name: Zephyr Docker Image CI
run-name: Here we build the Docker image used to build and develop Zephyr applications
on: [push]
jobs:
  build-and-publish-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build and push develop
        uses: spacebee-technologies/build-and-publish-action@v0.1.0
        with:
          registry-name: ${{ secrets.REGISTRY_NAME }}
          registry-certificate: ${{ secrets.REGISTRY_CERTIFICATE }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          image-name: rovertito/zephyr-environment
          image-tag: develop
  build-and-publish-tags:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build and push latest tag
        uses: spacebee-technologies/build-and-publish-action@v0.1.0
        with:
          registry-name: ${{ secrets.REGISTRY_NAME }}
          registry-certificate: ${{ secrets.REGISTRY_CERTIFICATE }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          image-name: rovertito/zephyr-environment
          image-tag: ${{ github.ref_name }}
          is-latest: true
