name: Zephyr Docker Image CI
run-name: Here we build the Docker image used to build our Rovertito application 🚀
on: [push]
jobs:
  build-and-publish-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Add CA certificate for registry
        run: |
          echo "${{ secrets.REGISTRY_CERTIFICATE }}" > ca.crt
          sudo mkdir -p /etc/docker/certs.d/${{ secrets.REGISTRY_NAME }}
          sudo cp ca.crt /etc/docker/certs.d/${{ secrets.REGISTRY_NAME }}
          sudo cp ca.crt /usr/local/share/ca-certificates/
          sudo update-ca-certificates
      - name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_NAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.spacebeetech.com/rovertito/zephyr-environment:develop
  build-and-publish-tags:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Add CA certificate for registry
        run: |
          echo "${{ secrets.REGISTRY_CERTIFICATE }}" > ca.crt
          sudo mkdir -p /etc/docker/certs.d/${{ secrets.REGISTRY_NAME }}
          sudo mv ca.crt /etc/docker/certs.d/${{ secrets.REGISTRY_NAME }}
      - name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_NAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ secrets.REGISTRY_NAME }}/rovertito/zephyr-environment:latest
            ${{ secrets.REGISTRY_NAME }}/rovertito/zephyr-environment:${{ github.ref_name }}
